POST http://localhost:3000/createTable/
Content-Type: application/json

###

POST http://localhost:3000/insertTodo/
Content-Type: application/json

###

GET http://localhost:3000/todos/

###

PUT http://localhost:3000/todos/

###

POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

###

DELETE http://localhost:3000/todos/10/

###

PUT http://localhost:3000/todos/1/
Content-Type: application/json

{
  "priority": "LOW"
}

###
